---
# This yml has NACL Settings
Resources:
  SimpleNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !ImportValue SimpleVPC

  SimpleNACLIngressSSH:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref SimpleNACL
      RuleNumber: 1
      Protocol: 6 # TCP
      PortRange:
        From: 22
        To: 22
      CidrBlock: 0.0.0.0/0
      RuleAction: allow

  SimpleNACLIngressHTTP:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref SimpleNACL
      RuleNumber: 10
      Protocol: 6 # TCP
      PortRange:
        From: 80
        To: 80
      CidrBlock: 0.0.0.0/0
      RuleAction: allow

  SimpleNACLIngressHTTPS:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref SimpleNACL
      RuleNumber: 11
      Protocol: 6 # TCP
      PortRange:
        From: 443
        To: 443
      CidrBlock: 0.0.0.0/0
      RuleAction: allow

  SimpleNACLEgressHTTP:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref SimpleNACL
      RuleNumber: 10
      Protocol: 6 # TCP
      PortRange:
        From: 80
        To: 80
      CidrBlock: 0.0.0.0/0
      RuleAction: allow
      Egress: true

  SimpleNACLEgressHTTPS:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref SimpleNACL
      RuleNumber: 11
      Protocol: 6
      PortRange:
        From: 443
        To: 443
      CidrBlock: 0.0.0.0/0
      RuleAction: allow
      Egress: true

  SimpleNACLEgressTemp:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref SimpleNACL
      RuleNumber: 100
      Protocol: 6
      PortRange:
        From: 32768
        To: 65535
      CidrBlock: 0.0.0.0/0
      RuleAction: allow
      Egress: true

Outputs:
  SimpleNACL:
    Description: Simple NACL
    Value: !Ref SimpleNACL
    Export:
      Name: SimpleNACL
